from setuptools import setup

setup(
    name='ai-nlp',
    version='1.0',
    packages=['env.Lib.site-packages.pip', 'env.Lib.site-packages.pip._vendor',
              'env.Lib.site-packages.pip._vendor.idna', 'env.Lib.site-packages.pip._vendor.pep517',
              'env.Lib.site-packages.pip._vendor.pytoml', 'env.Lib.site-packages.pip._vendor.certifi',
              'env.Lib.site-packages.pip._vendor.chardet', 'env.Lib.site-packages.pip._vendor.chardet.cli',
              'env.Lib.site-packages.pip._vendor.distlib', 'env.Lib.site-packages.pip._vendor.distlib._backport',
              'env.Lib.site-packages.pip._vendor.msgpack', 'env.Lib.site-packages.pip._vendor.urllib3',
              'env.Lib.site-packages.pip._vendor.urllib3.util', 'env.Lib.site-packages.pip._vendor.urllib3.contrib',
              'env.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.Lib.site-packages.pip._vendor.urllib3.packages',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.pip._vendor.colorama', 'env.Lib.site-packages.pip._vendor.html5lib',
              'env.Lib.site-packages.pip._vendor.html5lib._trie', 'env.Lib.site-packages.pip._vendor.html5lib.filters',
              'env.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'env.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'env.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'env.Lib.site-packages.pip._vendor.lockfile',
              'env.Lib.site-packages.pip._vendor.progress', 'env.Lib.site-packages.pip._vendor.requests',
              'env.Lib.site-packages.pip._vendor.packaging', 'env.Lib.site-packages.pip._vendor.cachecontrol',
              'env.Lib.site-packages.pip._vendor.cachecontrol.caches', 'env.Lib.site-packages.pip._vendor.webencodings',
              'env.Lib.site-packages.pip._vendor.pkg_resources', 'env.Lib.site-packages.pip._internal',
              'env.Lib.site-packages.pip._internal.cli', 'env.Lib.site-packages.pip._internal.req',
              'env.Lib.site-packages.pip._internal.vcs', 'env.Lib.site-packages.pip._internal.utils',
              'env.Lib.site-packages.pip._internal.models', 'env.Lib.site-packages.pip._internal.commands',
              'env.Lib.site-packages.pip._internal.operations', 'env.Lib.site-packages.blis',
              'env.Lib.site-packages.blis.tests', 'env.Lib.site-packages.boto', 'env.Lib.site-packages.boto.gs',
              'env.Lib.site-packages.boto.s3', 'env.Lib.site-packages.boto.ec2', 'env.Lib.site-packages.boto.ec2.elb',
              'env.Lib.site-packages.boto.ec2.autoscale', 'env.Lib.site-packages.boto.ec2.cloudwatch',
              'env.Lib.site-packages.boto.ecs', 'env.Lib.site-packages.boto.emr', 'env.Lib.site-packages.boto.fps',
              'env.Lib.site-packages.boto.iam', 'env.Lib.site-packages.boto.kms', 'env.Lib.site-packages.boto.mws',
              'env.Lib.site-packages.boto.rds', 'env.Lib.site-packages.boto.sdb', 'env.Lib.site-packages.boto.sdb.db',
              'env.Lib.site-packages.boto.sdb.db.manager', 'env.Lib.site-packages.boto.ses',
              'env.Lib.site-packages.boto.sns', 'env.Lib.site-packages.boto.sqs', 'env.Lib.site-packages.boto.sts',
              'env.Lib.site-packages.boto.swf', 'env.Lib.site-packages.boto.vpc', 'env.Lib.site-packages.boto.file',
              'env.Lib.site-packages.boto.logs', 'env.Lib.site-packages.boto.rds2', 'env.Lib.site-packages.boto.mturk',
              'env.Lib.site-packages.boto.pyami', 'env.Lib.site-packages.boto.pyami.installers',
              'env.Lib.site-packages.boto.pyami.installers.ubuntu', 'env.Lib.site-packages.boto.manage',
              'env.Lib.site-packages.boto.roboto', 'env.Lib.site-packages.boto.cacerts',
              'env.Lib.site-packages.boto.cognito', 'env.Lib.site-packages.boto.cognito.sync',
              'env.Lib.site-packages.boto.cognito.identity', 'env.Lib.site-packages.boto.contrib',
              'env.Lib.site-packages.boto.glacier', 'env.Lib.site-packages.boto.kinesis',
              'env.Lib.site-packages.boto.mashups', 'env.Lib.site-packages.boto.route53',
              'env.Lib.site-packages.boto.route53.domains', 'env.Lib.site-packages.boto.support',
              'env.Lib.site-packages.boto.cloudhsm', 'env.Lib.site-packages.boto.dynamodb',
              'env.Lib.site-packages.boto.opsworks', 'env.Lib.site-packages.boto.redshift',
              'env.Lib.site-packages.boto.services', 'env.Lib.site-packages.boto.vendored',
              'env.Lib.site-packages.boto.vendored.regions', 'env.Lib.site-packages.boto.awslambda',
              'env.Lib.site-packages.boto.beanstalk', 'env.Lib.site-packages.boto.dynamodb2',
              'env.Lib.site-packages.boto.cloudfront', 'env.Lib.site-packages.boto.cloudtrail',
              'env.Lib.site-packages.boto.codedeploy', 'env.Lib.site-packages.boto.cloudsearch',
              'env.Lib.site-packages.boto.elasticache', 'env.Lib.site-packages.boto.cloudsearch2',
              'env.Lib.site-packages.boto.datapipeline', 'env.Lib.site-packages.boto.configservice',
              'env.Lib.site-packages.boto.directconnect', 'env.Lib.site-packages.boto.cloudformation',
              'env.Lib.site-packages.boto.machinelearning', 'env.Lib.site-packages.boto.cloudsearchdomain',
              'env.Lib.site-packages.boto.elastictranscoder', 'env.Lib.site-packages.boto.ec2containerservice',
              'env.Lib.site-packages.idna', 'env.Lib.site-packages.nltk', 'env.Lib.site-packages.nltk.lm',
              'env.Lib.site-packages.nltk.app', 'env.Lib.site-packages.nltk.ccg', 'env.Lib.site-packages.nltk.sem',
              'env.Lib.site-packages.nltk.tag', 'env.Lib.site-packages.nltk.tbl', 'env.Lib.site-packages.nltk.chat',
              'env.Lib.site-packages.nltk.draw', 'env.Lib.site-packages.nltk.misc', 'env.Lib.site-packages.nltk.stem',
              'env.Lib.site-packages.nltk.test', 'env.Lib.site-packages.nltk.test.unit',
              'env.Lib.site-packages.nltk.test.unit.lm', 'env.Lib.site-packages.nltk.test.unit.translate',
              'env.Lib.site-packages.nltk.chunk', 'env.Lib.site-packages.nltk.parse',
              'env.Lib.site-packages.nltk.corpus', 'env.Lib.site-packages.nltk.corpus.reader',
              'env.Lib.site-packages.nltk.cluster', 'env.Lib.site-packages.nltk.metrics',
              'env.Lib.site-packages.nltk.twitter', 'env.Lib.site-packages.nltk.classify',
              'env.Lib.site-packages.nltk.tokenize', 'env.Lib.site-packages.nltk.inference',
              'env.Lib.site-packages.nltk.sentiment', 'env.Lib.site-packages.nltk.translate',
              'env.Lib.site-packages.pytz', 'env.Lib.site-packages.tqdm', 'env.Lib.site-packages.tqdm.auto',
              'env.Lib.site-packages.tqdm.autonotebook', 'env.Lib.site-packages.boto3',
              'env.Lib.site-packages.boto3.s3', 'env.Lib.site-packages.boto3.ec2', 'env.Lib.site-packages.boto3.docs',
              'env.Lib.site-packages.boto3.dynamodb', 'env.Lib.site-packages.boto3.resources',
              'env.Lib.site-packages.click', 'env.Lib.site-packages.cymem', 'env.Lib.site-packages.flask',
              'env.Lib.site-packages.flask.json', 'env.Lib.site-packages.numpy', 'env.Lib.site-packages.numpy.ma',
              'env.Lib.site-packages.numpy.ma.tests', 'env.Lib.site-packages.numpy.doc',
              'env.Lib.site-packages.numpy.fft', 'env.Lib.site-packages.numpy.fft.tests',
              'env.Lib.site-packages.numpy.lib', 'env.Lib.site-packages.numpy.lib.tests',
              'env.Lib.site-packages.numpy.core', 'env.Lib.site-packages.numpy.core.tests',
              'env.Lib.site-packages.numpy.f2py', 'env.Lib.site-packages.numpy.f2py.tests',
              'env.Lib.site-packages.numpy.tests', 'env.Lib.site-packages.numpy.compat',
              'env.Lib.site-packages.numpy.compat.tests', 'env.Lib.site-packages.numpy.linalg',
              'env.Lib.site-packages.numpy.linalg.tests', 'env.Lib.site-packages.numpy.random',
              'env.Lib.site-packages.numpy.random.tests', 'env.Lib.site-packages.numpy.testing',
              'env.Lib.site-packages.numpy.testing.tests', 'env.Lib.site-packages.numpy.testing._private',
              'env.Lib.site-packages.numpy.distutils', 'env.Lib.site-packages.numpy.distutils.tests',
              'env.Lib.site-packages.numpy.distutils.command', 'env.Lib.site-packages.numpy.distutils.fcompiler',
              'env.Lib.site-packages.numpy.matrixlib', 'env.Lib.site-packages.numpy.matrixlib.tests',
              'env.Lib.site-packages.numpy.polynomial', 'env.Lib.site-packages.numpy.polynomial.tests',
              'env.Lib.site-packages.scipy', 'env.Lib.site-packages.scipy.io', 'env.Lib.site-packages.scipy.io.arff',
              'env.Lib.site-packages.scipy.io.arff.tests', 'env.Lib.site-packages.scipy.io.tests',
              'env.Lib.site-packages.scipy.io.matlab', 'env.Lib.site-packages.scipy.io.matlab.tests',
              'env.Lib.site-packages.scipy.io.harwell_boeing', 'env.Lib.site-packages.scipy.io.harwell_boeing.tests',
              'env.Lib.site-packages.scipy.odr', 'env.Lib.site-packages.scipy.odr.tests',
              'env.Lib.site-packages.scipy._lib', 'env.Lib.site-packages.scipy._lib.tests',
              'env.Lib.site-packages.scipy.misc', 'env.Lib.site-packages.scipy.misc.tests',
              'env.Lib.site-packages.scipy.stats', 'env.Lib.site-packages.scipy.stats.tests',
              'env.Lib.site-packages.scipy.linalg', 'env.Lib.site-packages.scipy.linalg.tests',
              'env.Lib.site-packages.scipy.signal', 'env.Lib.site-packages.scipy.signal.tests',
              'env.Lib.site-packages.scipy.signal.windows', 'env.Lib.site-packages.scipy.sparse',
              'env.Lib.site-packages.scipy.sparse.tests', 'env.Lib.site-packages.scipy.sparse.linalg',
              'env.Lib.site-packages.scipy.sparse.linalg.eigen',
              'env.Lib.site-packages.scipy.sparse.linalg.eigen.arpack',
              'env.Lib.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'env.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'env.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'env.Lib.site-packages.scipy.sparse.linalg.tests', 'env.Lib.site-packages.scipy.sparse.linalg.dsolve',
              'env.Lib.site-packages.scipy.sparse.linalg.dsolve.tests',
              'env.Lib.site-packages.scipy.sparse.linalg.isolve',
              'env.Lib.site-packages.scipy.sparse.linalg.isolve.tests', 'env.Lib.site-packages.scipy.sparse.csgraph',
              'env.Lib.site-packages.scipy.sparse.csgraph.tests', 'env.Lib.site-packages.scipy.cluster',
              'env.Lib.site-packages.scipy.cluster.tests', 'env.Lib.site-packages.scipy.fftpack',
              'env.Lib.site-packages.scipy.fftpack.tests', 'env.Lib.site-packages.scipy.ndimage',
              'env.Lib.site-packages.scipy.ndimage.tests', 'env.Lib.site-packages.scipy.spatial',
              'env.Lib.site-packages.scipy.spatial.tests', 'env.Lib.site-packages.scipy.spatial.transform',
              'env.Lib.site-packages.scipy.spatial.transform.tests', 'env.Lib.site-packages.scipy.special',
              'env.Lib.site-packages.scipy.special.tests', 'env.Lib.site-packages.scipy.special._precompute',
              'env.Lib.site-packages.scipy.optimize', 'env.Lib.site-packages.scipy.optimize._lsq',
              'env.Lib.site-packages.scipy.optimize.tests', 'env.Lib.site-packages.scipy.optimize._trlib',
              'env.Lib.site-packages.scipy.optimize._shgo_lib',
              'env.Lib.site-packages.scipy.optimize._trustregion_constr',
              'env.Lib.site-packages.scipy.optimize._trustregion_constr.tests', 'env.Lib.site-packages.scipy.constants',
              'env.Lib.site-packages.scipy.constants.tests', 'env.Lib.site-packages.scipy.integrate',
              'env.Lib.site-packages.scipy.integrate._ivp', 'env.Lib.site-packages.scipy.integrate.tests',
              'env.Lib.site-packages.scipy.interpolate', 'env.Lib.site-packages.scipy.interpolate.tests',
              'env.Lib.site-packages.scipy._build_utils', 'env.Lib.site-packages.spacy',
              'env.Lib.site-packages.spacy.cli', 'env.Lib.site-packages.spacy.cli.converters',
              'env.Lib.site-packages.spacy.data', 'env.Lib.site-packages.spacy.lang',
              'env.Lib.site-packages.spacy.lang.af', 'env.Lib.site-packages.spacy.lang.ar',
              'env.Lib.site-packages.spacy.lang.bg', 'env.Lib.site-packages.spacy.lang.bn',
              'env.Lib.site-packages.spacy.lang.ca', 'env.Lib.site-packages.spacy.lang.cs',
              'env.Lib.site-packages.spacy.lang.da', 'env.Lib.site-packages.spacy.lang.de',
              'env.Lib.site-packages.spacy.lang.el', 'env.Lib.site-packages.spacy.lang.el.lemmatizer',
              'env.Lib.site-packages.spacy.lang.en', 'env.Lib.site-packages.spacy.lang.en.lemmatizer',
              'env.Lib.site-packages.spacy.lang.es', 'env.Lib.site-packages.spacy.lang.et',
              'env.Lib.site-packages.spacy.lang.fa', 'env.Lib.site-packages.spacy.lang.fa.lemmatizer',
              'env.Lib.site-packages.spacy.lang.fi', 'env.Lib.site-packages.spacy.lang.fr',
              'env.Lib.site-packages.spacy.lang.fr.lemmatizer', 'env.Lib.site-packages.spacy.lang.ga',
              'env.Lib.site-packages.spacy.lang.he', 'env.Lib.site-packages.spacy.lang.hi',
              'env.Lib.site-packages.spacy.lang.hr', 'env.Lib.site-packages.spacy.lang.hu',
              'env.Lib.site-packages.spacy.lang.id', 'env.Lib.site-packages.spacy.lang.is',
              'env.Lib.site-packages.spacy.lang.it', 'env.Lib.site-packages.spacy.lang.ja',
              'env.Lib.site-packages.spacy.lang.kn', 'env.Lib.site-packages.spacy.lang.lt',
              'env.Lib.site-packages.spacy.lang.lv', 'env.Lib.site-packages.spacy.lang.nb',
              'env.Lib.site-packages.spacy.lang.nb.lemmatizer', 'env.Lib.site-packages.spacy.lang.nl',
              'env.Lib.site-packages.spacy.lang.pl', 'env.Lib.site-packages.spacy.lang.pt',
              'env.Lib.site-packages.spacy.lang.ro', 'env.Lib.site-packages.spacy.lang.ru',
              'env.Lib.site-packages.spacy.lang.si', 'env.Lib.site-packages.spacy.lang.sk',
              'env.Lib.site-packages.spacy.lang.sl', 'env.Lib.site-packages.spacy.lang.sq',
              'env.Lib.site-packages.spacy.lang.sv', 'env.Lib.site-packages.spacy.lang.sv.lemmatizer',
              'env.Lib.site-packages.spacy.lang.ta', 'env.Lib.site-packages.spacy.lang.te',
              'env.Lib.site-packages.spacy.lang.th', 'env.Lib.site-packages.spacy.lang.tl',
              'env.Lib.site-packages.spacy.lang.tr', 'env.Lib.site-packages.spacy.lang.tt',
              'env.Lib.site-packages.spacy.lang.uk', 'env.Lib.site-packages.spacy.lang.ur',
              'env.Lib.site-packages.spacy.lang.vi', 'env.Lib.site-packages.spacy.lang.xx',
              'env.Lib.site-packages.spacy.lang.zh', 'env.Lib.site-packages.spacy.tests',
              'env.Lib.site-packages.spacy.tests.doc', 'env.Lib.site-packages.spacy.tests.lang',
              'env.Lib.site-packages.spacy.tests.lang.ar', 'env.Lib.site-packages.spacy.tests.lang.bn',
              'env.Lib.site-packages.spacy.tests.lang.ca', 'env.Lib.site-packages.spacy.tests.lang.da',
              'env.Lib.site-packages.spacy.tests.lang.de', 'env.Lib.site-packages.spacy.tests.lang.el',
              'env.Lib.site-packages.spacy.tests.lang.en', 'env.Lib.site-packages.spacy.tests.lang.es',
              'env.Lib.site-packages.spacy.tests.lang.fi', 'env.Lib.site-packages.spacy.tests.lang.fr',
              'env.Lib.site-packages.spacy.tests.lang.ga', 'env.Lib.site-packages.spacy.tests.lang.he',
              'env.Lib.site-packages.spacy.tests.lang.hu', 'env.Lib.site-packages.spacy.tests.lang.id',
              'env.Lib.site-packages.spacy.tests.lang.it', 'env.Lib.site-packages.spacy.tests.lang.ja',
              'env.Lib.site-packages.spacy.tests.lang.nb', 'env.Lib.site-packages.spacy.tests.lang.nl',
              'env.Lib.site-packages.spacy.tests.lang.pl', 'env.Lib.site-packages.spacy.tests.lang.pt',
              'env.Lib.site-packages.spacy.tests.lang.ro', 'env.Lib.site-packages.spacy.tests.lang.ru',
              'env.Lib.site-packages.spacy.tests.lang.sv', 'env.Lib.site-packages.spacy.tests.lang.th',
              'env.Lib.site-packages.spacy.tests.lang.tr', 'env.Lib.site-packages.spacy.tests.lang.tt',
              'env.Lib.site-packages.spacy.tests.lang.uk', 'env.Lib.site-packages.spacy.tests.lang.ur',
              'env.Lib.site-packages.spacy.tests.parser', 'env.Lib.site-packages.spacy.tests.matcher',
              'env.Lib.site-packages.spacy.tests.pipeline', 'env.Lib.site-packages.spacy.tests.serialize',
              'env.Lib.site-packages.spacy.tests.tokenizer', 'env.Lib.site-packages.spacy.tests.regression',
              'env.Lib.site-packages.spacy.tests.vocab_vectors', 'env.Lib.site-packages.spacy.syntax',
              'env.Lib.site-packages.spacy.tokens', 'env.Lib.site-packages.spacy.matcher',
              'env.Lib.site-packages.spacy.displacy', 'env.Lib.site-packages.spacy.pipeline',
              'env.Lib.site-packages.srsly', 'env.Lib.site-packages.srsly.tests',
              'env.Lib.site-packages.srsly.tests.ujson', 'env.Lib.site-packages.srsly.tests.msgpack',
              'env.Lib.site-packages.srsly.tests.cloudpickle', 'env.Lib.site-packages.srsly.ujson',
              'env.Lib.site-packages.srsly.msgpack', 'env.Lib.site-packages.srsly.cloudpickle',
              'env.Lib.site-packages.thinc', 'env.Lib.site-packages.thinc.extra',
              'env.Lib.site-packages.thinc.extra.wrapt', 'env.Lib.site-packages.thinc.extra._vendorized',
              'env.Lib.site-packages.thinc.tests', 'env.Lib.site-packages.thinc.tests.unit',
              'env.Lib.site-packages.thinc.tests.linear', 'env.Lib.site-packages.thinc.tests.integration',
              'env.Lib.site-packages.thinc.linear', 'env.Lib.site-packages.thinc.neural',
              'env.Lib.site-packages.thinc.neural._classes', 'env.Lib.site-packages.gensim',
              'env.Lib.site-packages.gensim.viz', 'env.Lib.site-packages.gensim.test',
              'env.Lib.site-packages.gensim.models', 'env.Lib.site-packages.gensim.models.wrappers',
              'env.Lib.site-packages.gensim.models.deprecated', 'env.Lib.site-packages.gensim.corpora',
              'env.Lib.site-packages.gensim.parsing', 'env.Lib.site-packages.gensim.scripts',
              'env.Lib.site-packages.gensim.sklearn_api', 'env.Lib.site-packages.gensim.similarities',
              'env.Lib.site-packages.gensim.summarization', 'env.Lib.site-packages.gensim.topic_coherence',
              'env.Lib.site-packages.jinja2', 'env.Lib.site-packages.pandas', 'env.Lib.site-packages.pandas.io',
              'env.Lib.site-packages.pandas.io.sas', 'env.Lib.site-packages.pandas.io.json',
              'env.Lib.site-packages.pandas.io.formats', 'env.Lib.site-packages.pandas.io.msgpack',
              'env.Lib.site-packages.pandas.io.clipboard', 'env.Lib.site-packages.pandas.api',
              'env.Lib.site-packages.pandas.api.types', 'env.Lib.site-packages.pandas.api.extensions',
              'env.Lib.site-packages.pandas.core', 'env.Lib.site-packages.pandas.core.util',
              'env.Lib.site-packages.pandas.core.tools', 'env.Lib.site-packages.pandas.core.arrays',
              'env.Lib.site-packages.pandas.core.dtypes', 'env.Lib.site-packages.pandas.core.sparse',
              'env.Lib.site-packages.pandas.core.groupby', 'env.Lib.site-packages.pandas.core.indexes',
              'env.Lib.site-packages.pandas.core.reshape', 'env.Lib.site-packages.pandas.core.internals',
              'env.Lib.site-packages.pandas.core.computation', 'env.Lib.site-packages.pandas.util',
              'env.Lib.site-packages.pandas._libs', 'env.Lib.site-packages.pandas._libs.tslibs',
              'env.Lib.site-packages.pandas.tests', 'env.Lib.site-packages.pandas.tests.io',
              'env.Lib.site-packages.pandas.tests.io.sas', 'env.Lib.site-packages.pandas.tests.io.json',
              'env.Lib.site-packages.pandas.tests.io.parser', 'env.Lib.site-packages.pandas.tests.io.formats',
              'env.Lib.site-packages.pandas.tests.io.msgpack', 'env.Lib.site-packages.pandas.tests.api',
              'env.Lib.site-packages.pandas.tests.util', 'env.Lib.site-packages.pandas.tests.frame',
              'env.Lib.site-packages.pandas.tests.tools', 'env.Lib.site-packages.pandas.tests.arrays',
              'env.Lib.site-packages.pandas.tests.arrays.sparse', 'env.Lib.site-packages.pandas.tests.arrays.interval',
              'env.Lib.site-packages.pandas.tests.arrays.categorical', 'env.Lib.site-packages.pandas.tests.dtypes',
              'env.Lib.site-packages.pandas.tests.dtypes.cast', 'env.Lib.site-packages.pandas.tests.scalar',
              'env.Lib.site-packages.pandas.tests.scalar.period', 'env.Lib.site-packages.pandas.tests.scalar.interval',
              'env.Lib.site-packages.pandas.tests.scalar.timedelta',
              'env.Lib.site-packages.pandas.tests.scalar.timestamp', 'env.Lib.site-packages.pandas.tests.series',
              'env.Lib.site-packages.pandas.tests.series.indexing', 'env.Lib.site-packages.pandas.tests.sparse',
              'env.Lib.site-packages.pandas.tests.sparse.frame', 'env.Lib.site-packages.pandas.tests.sparse.series',
              'env.Lib.site-packages.pandas.tests.tslibs', 'env.Lib.site-packages.pandas.tests.generic',
              'env.Lib.site-packages.pandas.tests.groupby', 'env.Lib.site-packages.pandas.tests.groupby.aggregate',
              'env.Lib.site-packages.pandas.tests.indexes', 'env.Lib.site-packages.pandas.tests.indexes.multi',
              'env.Lib.site-packages.pandas.tests.indexes.period',
              'env.Lib.site-packages.pandas.tests.indexes.interval',
              'env.Lib.site-packages.pandas.tests.indexes.datetimes',
              'env.Lib.site-packages.pandas.tests.indexes.timedeltas', 'env.Lib.site-packages.pandas.tests.reshape',
              'env.Lib.site-packages.pandas.tests.reshape.merge', 'env.Lib.site-packages.pandas.tests.tseries',
              'env.Lib.site-packages.pandas.tests.tseries.offsets', 'env.Lib.site-packages.pandas.tests.indexing',
              'env.Lib.site-packages.pandas.tests.indexing.interval',
              'env.Lib.site-packages.pandas.tests.indexing.multiindex', 'env.Lib.site-packages.pandas.tests.plotting',
              'env.Lib.site-packages.pandas.tests.resample', 'env.Lib.site-packages.pandas.tests.extension',
              'env.Lib.site-packages.pandas.tests.extension.base', 'env.Lib.site-packages.pandas.tests.extension.json',
              'env.Lib.site-packages.pandas.tests.extension.arrow',
              'env.Lib.site-packages.pandas.tests.extension.numpy_',
              'env.Lib.site-packages.pandas.tests.extension.decimal', 'env.Lib.site-packages.pandas.tests.internals',
              'env.Lib.site-packages.pandas.tests.arithmetic', 'env.Lib.site-packages.pandas.tests.reductions',
              'env.Lib.site-packages.pandas.tests.computation', 'env.Lib.site-packages.pandas.arrays',
              'env.Lib.site-packages.pandas.compat', 'env.Lib.site-packages.pandas.compat.numpy',
              'env.Lib.site-packages.pandas.errors', 'env.Lib.site-packages.pandas.tseries',
              'env.Lib.site-packages.pandas.plotting', 'env.Lib.site-packages.wasabi',
              'env.Lib.site-packages.wasabi.tests', 'env.Lib.site-packages.certifi', 'env.Lib.site-packages.chardet',
              'env.Lib.site-packages.chardet.cli', 'env.Lib.site-packages.preshed',
              'env.Lib.site-packages.preshed.tests', 'env.Lib.site-packages.sklearn',
              'env.Lib.site-packages.sklearn.svm', 'env.Lib.site-packages.sklearn.svm.tests',
              'env.Lib.site-packages.sklearn.tree', 'env.Lib.site-packages.sklearn.tree.tests',
              'env.Lib.site-packages.sklearn.tests', 'env.Lib.site-packages.sklearn.utils',
              'env.Lib.site-packages.sklearn.utils.tests', 'env.Lib.site-packages.sklearn.utils.sparsetools',
              'env.Lib.site-packages.sklearn.utils.sparsetools.tests', 'env.Lib.site-packages.sklearn.cluster',
              'env.Lib.site-packages.sklearn.cluster.tests', 'env.Lib.site-packages.sklearn.compose',
              'env.Lib.site-packages.sklearn.compose.tests', 'env.Lib.site-packages.sklearn.metrics',
              'env.Lib.site-packages.sklearn.metrics.tests', 'env.Lib.site-packages.sklearn.metrics.cluster',
              'env.Lib.site-packages.sklearn.metrics.cluster.tests', 'env.Lib.site-packages.sklearn.mixture',
              'env.Lib.site-packages.sklearn.mixture.tests', 'env.Lib.site-packages.sklearn.datasets',
              'env.Lib.site-packages.sklearn.datasets.tests', 'env.Lib.site-packages.sklearn.ensemble',
              'env.Lib.site-packages.sklearn.ensemble.tests', 'env.Lib.site-packages.sklearn.manifold',
              'env.Lib.site-packages.sklearn.manifold.tests', 'env.Lib.site-packages.sklearn.externals',
              'env.Lib.site-packages.sklearn.externals.joblib',
              'env.Lib.site-packages.sklearn.externals.joblib.externals',
              'env.Lib.site-packages.sklearn.externals.joblib.externals.loky',
              'env.Lib.site-packages.sklearn.externals.joblib.externals.loky.backend',
              'env.Lib.site-packages.sklearn.externals.joblib.externals.cloudpickle',
              'env.Lib.site-packages.sklearn.neighbors', 'env.Lib.site-packages.sklearn.neighbors.tests',
              'env.Lib.site-packages.sklearn.covariance', 'env.Lib.site-packages.sklearn.covariance.tests',
              'env.Lib.site-packages.sklearn._build_utils', 'env.Lib.site-packages.sklearn.linear_model',
              'env.Lib.site-packages.sklearn.linear_model.tests', 'env.Lib.site-packages.sklearn.__check_build',
              'env.Lib.site-packages.sklearn.decomposition', 'env.Lib.site-packages.sklearn.decomposition.tests',
              'env.Lib.site-packages.sklearn.preprocessing', 'env.Lib.site-packages.sklearn.preprocessing.tests',
              'env.Lib.site-packages.sklearn.neural_network', 'env.Lib.site-packages.sklearn.neural_network.tests',
              'env.Lib.site-packages.sklearn.model_selection', 'env.Lib.site-packages.sklearn.model_selection.tests',
              'env.Lib.site-packages.sklearn.semi_supervised', 'env.Lib.site-packages.sklearn.semi_supervised.tests',
              'env.Lib.site-packages.sklearn.gaussian_process', 'env.Lib.site-packages.sklearn.gaussian_process.tests',
              'env.Lib.site-packages.sklearn.feature_selection',
              'env.Lib.site-packages.sklearn.feature_selection.tests',
              'env.Lib.site-packages.sklearn.feature_extraction',
              'env.Lib.site-packages.sklearn.feature_extraction.tests',
              'env.Lib.site-packages.sklearn.cross_decomposition',
              'env.Lib.site-packages.sklearn.cross_decomposition.tests', 'env.Lib.site-packages.urllib3',
              'env.Lib.site-packages.urllib3.util', 'env.Lib.site-packages.urllib3.contrib',
              'env.Lib.site-packages.urllib3.contrib._securetransport', 'env.Lib.site-packages.urllib3.packages',
              'env.Lib.site-packages.urllib3.packages.backports',
              'env.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'env.Lib.site-packages.botocore',
              'env.Lib.site-packages.botocore.docs', 'env.Lib.site-packages.botocore.docs.bcdoc',
              'env.Lib.site-packages.botocore.vendored', 'env.Lib.site-packages.botocore.vendored.requests',
              'env.Lib.site-packages.botocore.vendored.requests.packages',
              'env.Lib.site-packages.botocore.vendored.requests.packages.chardet',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3.util',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3.contrib',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3.packages',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.dateutil', 'env.Lib.site-packages.dateutil.tz',
              'env.Lib.site-packages.dateutil.parser', 'env.Lib.site-packages.dateutil.zoneinfo',
              'env.Lib.site-packages.docutils', 'env.Lib.site-packages.docutils.utils',
              'env.Lib.site-packages.docutils.utils.math', 'env.Lib.site-packages.docutils.parsers',
              'env.Lib.site-packages.docutils.parsers.rst', 'env.Lib.site-packages.docutils.parsers.rst.languages',
              'env.Lib.site-packages.docutils.parsers.rst.directives', 'env.Lib.site-packages.docutils.readers',
              'env.Lib.site-packages.docutils.writers', 'env.Lib.site-packages.docutils.writers.xetex',
              'env.Lib.site-packages.docutils.writers.latex2e', 'env.Lib.site-packages.docutils.writers.odf_odt',
              'env.Lib.site-packages.docutils.writers.s5_html', 'env.Lib.site-packages.docutils.writers.pep_html',
              'env.Lib.site-packages.docutils.writers.html4css1',
              'env.Lib.site-packages.docutils.writers.html5_polyglot', 'env.Lib.site-packages.docutils.languages',
              'env.Lib.site-packages.docutils.transforms', 'env.Lib.site-packages.jmespath',
              'env.Lib.site-packages.networkx', 'env.Lib.site-packages.networkx.tests',
              'env.Lib.site-packages.networkx.utils', 'env.Lib.site-packages.networkx.linalg',
              'env.Lib.site-packages.networkx.classes', 'env.Lib.site-packages.networkx.drawing',
              'env.Lib.site-packages.networkx.testing', 'env.Lib.site-packages.networkx.readwrite',
              'env.Lib.site-packages.networkx.readwrite.json_graph', 'env.Lib.site-packages.networkx.algorithms',
              'env.Lib.site-packages.networkx.algorithms.flow', 'env.Lib.site-packages.networkx.algorithms.tree',
              'env.Lib.site-packages.networkx.algorithms.tests', 'env.Lib.site-packages.networkx.algorithms.coloring',
              'env.Lib.site-packages.networkx.algorithms.bipartite',
              'env.Lib.site-packages.networkx.algorithms.community',
              'env.Lib.site-packages.networkx.algorithms.operators',
              'env.Lib.site-packages.networkx.algorithms.traversal',
              'env.Lib.site-packages.networkx.algorithms.centrality',
              'env.Lib.site-packages.networkx.algorithms.components',
              'env.Lib.site-packages.networkx.algorithms.isomorphism',
              'env.Lib.site-packages.networkx.algorithms.connectivity',
              'env.Lib.site-packages.networkx.algorithms.approximation',
              'env.Lib.site-packages.networkx.algorithms.assortativity',
              'env.Lib.site-packages.networkx.algorithms.link_analysis',
              'env.Lib.site-packages.networkx.algorithms.shortest_paths',
              'env.Lib.site-packages.networkx.algorithms.node_classification',
              'env.Lib.site-packages.networkx.generators', 'env.Lib.site-packages.requests',
              'env.Lib.site-packages.werkzeug', 'env.Lib.site-packages.werkzeug.debug',
              'env.Lib.site-packages.werkzeug.contrib', 'env.Lib.site-packages.werkzeug.wrappers',
              'env.Lib.site-packages.werkzeug.middleware', 'env.Lib.site-packages.jsonschema',
              'env.Lib.site-packages.jsonschema.tests', 'env.Lib.site-packages.markupsafe',
              'env.Lib.site-packages.matplotlib', 'env.Lib.site-packages.matplotlib.tri',
              'env.Lib.site-packages.matplotlib.axes', 'env.Lib.site-packages.matplotlib.cbook',
              'env.Lib.site-packages.matplotlib.style', 'env.Lib.site-packages.matplotlib.compat',
              'env.Lib.site-packages.matplotlib.testing', 'env.Lib.site-packages.matplotlib.testing.jpl_units',
              'env.Lib.site-packages.matplotlib.backends', 'env.Lib.site-packages.matplotlib.backends.qt_editor',
              'env.Lib.site-packages.matplotlib.sphinxext', 'env.Lib.site-packages.matplotlib.projections',
              'env.Lib.site-packages.murmurhash', 'env.Lib.site-packages.murmurhash.tests',
              'env.Lib.site-packages.s3transfer', 'env.Lib.site-packages.setuptools',
              'env.Lib.site-packages.setuptools.extern', 'env.Lib.site-packages.setuptools._vendor',
              'env.Lib.site-packages.setuptools._vendor.packaging', 'env.Lib.site-packages.setuptools.command',
              'env.Lib.site-packages.smart_open', 'env.Lib.site-packages.smart_open.tests',
              'env.Lib.site-packages.itsdangerous', 'env.Lib.site-packages.mpl_toolkits.mplot3d',
              'env.Lib.site-packages.mpl_toolkits.axes_grid', 'env.Lib.site-packages.mpl_toolkits.axes_grid1',
              'env.Lib.site-packages.mpl_toolkits.axisartist', 'env.Lib.site-packages.pkg_resources',
              'env.Lib.site-packages.pkg_resources.extern', 'env.Lib.site-packages.pkg_resources._vendor',
              'env.Lib.site-packages.pkg_resources._vendor.packaging', 'env.Lib.site-packages.en_core_web_sm',
              'env.Lib.site-packages.xx_ent_wiki_sm', 'env.Lib.site-packages.de_core_news_sm',
              'env.Lib.site-packages.es_core_news_sm', 'env.Lib.site-packages.fr_core_news_sm',
              'env.Lib.site-packages.it_core_news_sm', 'env.Lib.site-packages.pt_core_news_sm', 'templates'],
    url='',
    license='',
    author='sioschul',
    author_email='',
    description=''
)
