import itertools

import spacy
import nltk
from collections import Counter, OrderedDict
import pprint as pp

matched =[['Accio'],
 ['Ah'],
 ['Albus_Dumbledore', 'Dumbledore'],
 ['Alicia'],
 ['And_I'],
 ['Angelina'],
 ['Arthur', 'Arthur_Weasley'],
 ['Astronomy'],
 ['Atrium'],
 ['Aunt_Petunia', 'Petunia'],
 ['Auror'],
 ['Aurors'],
 ['Azkaban'],
 ['BANG'],
 ['Bane'],
 ['Bellatrix', 'Bellatrix_Lestrange'],
 ['Bill'],
 ['Binns'],
 ['Black', 'Sirius', 'Sirius_Black'],
 ['Black', 'Sirius', 'Sirius_Black'],
 ['Bludger'],
 ['Bode'],
 ['Boggart'],
 ['Bowtruckle'],
 ['Buckbeak'],
 ['Butterbeer'],
 ['Cedric', 'Cedric_Diggory'],
 ['Charms'],
 ['Cho', 'Cho_Chang'],
 ['Christmas'],
 ['Cloak', 'Invisibility_Cloak'],
 ['Come'],
 ['Cornelius', 'Cornelius_Fudge', 'Fudge'],
 ['Cornelius', 'Cornelius_Fudge', 'Fudge'],
 ['Course'],
 ['Crabbe'],
 ['Crack'],
 ['Crookshanks'],
 ["D'you"],
 ['DA'],
 ['Dad'],
 ['Daily_Prophet', 'Prophet'],
 ['Dark', 'Dark_Lord', 'Defence_Against_the_Dark_Arts'],
 ['Dark', 'Dark_Lord', 'Defence_Against_the_Dark_Arts'],
 ['Dawlish'],
 ['Dean', 'Dean_Thomas'],
 ['Death_Eater'],
 ['Death_Eaters'],
 ['Defensive_Magical_Theory'],
 ['Dementor'],
 ['Dementors'],
 ['Department_of_Mysteries'],
 ['Diagon_Alley'],
 ['Divination'],
 ['Dobby'],
 ['Dolohov'],
 ['Dolores', 'Dolores_Umbridge', 'Professor_Umbridge', 'Umbridge'],
 ['Doxys'],
 ['Draco', 'Draco_Malfoy', 'Malfoy'],
 ['Draco', 'Draco_Malfoy', 'Malfoy'],
 ['Dudley'],
 ['Dungbombs'],
 ['Dursleys'],
 ['Easter'],
 ['Educational_Decree_Number_Twenty'],
 ['English'],
 ['Entrance_Hall'],
 ['Erm'],
 ['Ernie', 'Ernie_Macmillan'],
 ['Extendable_Ears'],
 ['Eye_Moody', 'Moody'],
 ['Fang'],
 ['Fat_Lady'],
 ['Fawkes'],
 ['Filch'],
 ['Firebolt'],
 ['Firenze'],
 ['Flitwick', 'Professor_Flitwick'],
 ['Forbidden_Forest', 'Forest'],
 ['Fred'],
 ['Galleon'],
 ['Galleons'],
 ['George'],
 ['Gilderoy'],
 ['Ginny'],
 ['Golgomath'],
 ['Goyle'],
 ['Grawp'],
 ['Great_Hall', 'Hall'],
 ['Great_Hall', 'Hall'],
 ['Grimmauld_Place'],
 ['Grubbly', 'Professor_Grubbly'],
 ['Gryffindor', 'Gryffindor_Tower'],
 ['Gryffindors'],
 ['Gurg'],
 ['Hagrid'],
 ['Hannah_Abbott'],
 ['Harry', 'Harry_Potter', 'Mr_Potter', 'Potter'],
 ['He_Who_Must_Not_Be_Named'],
 ['Headmaster'],
 ['Headmistress'],
 ['Headquarters'],
 ['Healer'],
 ['Healers'],
 ['Hedwig'],
 ['Herbology'],
 ['Hermione', 'Hermione_Granger'],
 ['High_Inquisitor'],
 ['History_of_Magic'],
 ["Hog's_Head"],
 ['Hogsmeade'],
 ['Hogwarts'],
 ['Howler'],
 ['Hufflepuff'],
 ["I_s'pose"],
 ['Imperius_Curse'],
 ['Inquisitorial_Squad'],
 ['James'],
 ['Johnson'],
 ['Karkus'],
 ['Katie', 'Katie_Bell'],
 ['Keeper'],
 ['Kingsley', 'Kingsley_Shacklebolt'],
 ['Knight_Bus'],
 ['Kreacher'],
 ['Lavender'],
 ['Lee', 'Lee_Jordan'],
 ['Lily'],
 ['Little_Whinging'],
 ['Lockhart'],
 ['London'],
 ['Lord_Voldemort', 'Voldemort'],
 ['Lucius_Malfoy'],
 ['Luna', 'Luna_Lovegood'],
 ['Lupin'],
 ['Mad', 'Madam_Bones'],
 ['Mad', 'Madam_Bones'],
 ['Mad-Eye'],
 ['Madam_Hooch'],
 ['Madam_Pomfrey'],
 ['Magnolia_Crescent'],
 ['Magorian'],
 ['Marchbanks'],
 ['Marietta'],
 ['Maybe'],
 ['McGonagall', 'Professor_McGonagall'],
 ['Merlin'],
 ['Michael_Corner'],
 ['Minerva'],
 ['Minister', 'Minister_for_Magic'],
 ['Ministry', 'Ministry_of_Magic'],
 ['Miss_Edgecombe'],
 ['Miss_Granger'],
 ['Molly'],
 ['Montague'],
 ['Mr_Weasley'],
 ['Mrs_Figg'],
 ['Mrs_Longbottom'],
 ['Mrs_Norris'],
 ['Mrs_Weasley', 'Weasley'],
 ['Mrs_Weasley', 'Weasley'],
 ['Muggle'],
 ['Muggles'],
 ['Mundungus'],
 ['Murtlap'],
 ['NEWTs'],
 ['Nearly_Headless_Nick', 'Nick'],
 ['Neville'],
 ['OK'],
 ['OWL'],
 ['OWLs'],
 ['Occlumency'],
 ['Olympe'],
 ['Order', 'Order_of_the_Phoenix'],
 ['Owlery'],
 ['Pansy_Parkinson'],
 ['Parvati'],
 ['Patronus'],
 ['Peeves'],
 ['Pensieve'],
 ['Percy'],
 ['Phineas', 'Phineas_Nigellus'],
 ['Pigwidgeon'],
 ['Plank'],
 ['Portkey'],
 ['Potions'],
 ['Privet_Drive'],
 ['Professor_Trelawney', 'Trelawney'],
 ['Pucey'],
 ['Quaffle'],
 ['Quidditch'],
 ['Ravenclaw'],
 ['Remember'],
 ['Rita'],
 ['Roger_Davies'],
 ['Ron'],
 ['Rookwood'],
 ['Room_of_Requirement'],
 ['SIRIUS'],
 ['SPEW'],
 ['Seamus'],
 ['Shut'],
 ['Slytherin'],
 ['Slytherins'],
 ['Smith', 'Zacharias', 'Zacharias_Smith'],
 ['Smith', 'Zacharias', 'Zacharias_Smith'],
 ['Snape'],
 ['Snitch'],
 ['Sorry'],
 ['Sprout'],
 ['St_Mungo'],
 ['Stinksap'],
 ['Sybill'],
 ['Thank'],
 ['The_Ministry'],
 ['The_Quibbler'],
 ['Thestral'],
 ['Thestrals'],
 ['Three_Broomsticks'],
 ['Tofty'],
 ['Tonks'],
 ['Transfiguration'],
 ['Uncle_Vernon', 'Vernon'],
 ['WEASLEY'],
 ['Warrington'],
 ['Weasleys'],
 ['Wisteria_Walk'],
 ['Wizengamot'],
 ['Wormtail'],
 ['You-Know-Who']]

for idx, sublist in enumerate(matched):
    temp = list(dict.fromkeys(sublist))
    temp.sort()
    matched[idx] = temp
matched.sort()
matched = list(matched for matched, _ in itertools.groupby(matched))
print(matched)
# load model
nlp = spacy.load('en')

# read book
with open("Harry_Potter_and_the_Sorcerer.txt") as f:
    book = f.read()
# split book into sentences
sentences = nltk.tokenize.sent_tokenize(book)
tokens = []
sentences_by_ents = {}

for s in sentences:
    s = s.strip()
    doc = nlp(s)
    for token in doc:
        if token.pos_ == 'PROPN':
            # remove whitespaces from ents
            if "\n\n" not in token.text:
                # keep all sentences from the same entity together
                # assuming entities with the same name are always the same type/person in the same book
                sentences_by_ents.setdefault(token.text, []).append(s)
                # keep track of entities with their tag
                tokens.append((token.text, token.ent_type_))
c = Counter(tokens)
# remove unnecessary entries with <6 occurrences
most_common = {k: c[k] for k in c if c[k] > 6}
most_common_sentences = {k: sentences_by_ents[k] for k in sentences_by_ents if len(sentences_by_ents[k]) > 6}
pp.pprint(sorted(most_common.items(), key=lambda kv: kv[0]))

